### ISSUE TITLE
`brew file install` で JSONDecodeError が発生してしまう

### ISSUE THREAD

**Issue by phasmatodean** [rcmdnk/homebrew-file#105]
`brew file install` の実行で以下のようなエラーが突然出るようになってしまいました。
こちらは #45 と同様の事象でしょうか。
解決策がございましたらご教示いただきたいです。

ちなみに、`init` や `clean` のコマンドでも同様の事象が発生します。

```
$ brew file install
Traceback (most recent call last):
  File "/usr/local/bin/brew-file", line 3468, in <module>
    main()
  File "/usr/local/bin/brew-file", line 3462, in main
    b.execute()
  File "/usr/local/bin/brew-file", line 3092, in execute
    self.install()
  File "/usr/local/bin/brew-file", line 2374, in install
    self.get_list(force_appstore_list=True)
  File "/usr/local/bin/brew-file", line 1900, in get_list
    info = self.brewinfo.get_info()
  File "/usr/local/bin/brew-file", line 572, in get_info
    infotmp = json.loads(
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 2 (char 1)
```

**Comment by rcmdnk** [comment]
報告ありがとうございます。
私も今日自分の環境で起こっていることを確認して治さないと、とは思っているのですがまだちょっと手が付けられていない状態です。

#46と同じ様なエラーなんですが、
手元で直接該当部分の`brew info --json=v1 --installed`を書き出して見るとおかしなものは追加されておらず、
直接json.loadsしてみると問題なく読み込める状態です。

多分何か見落としてるのだと思うのですが、ちょっと早めに時間を取ってみてみるつもりではいます。

**Comment by rcmdnk** [comment]
`brew info --json=v1 --installed`の出力はJSON形式で問題なく出てはいたのですが
以前は全て1行で書き出されていたものがHomebrew 3.1.0から
Homebrew/brew@6f071a0
で見やすいように整形されて出力される様になったことが問題でした。

fixしましたのでbrew-fileをアップデートして試してみていただけますか?

**Comment by phasmatodean** [comment]
バージョン8.3.4にて `brew file init` が問題なく完了することを確認しました。
素早くご対応いただき、ありがとうございました。
