### ISSUE TITLE
KeyError: 'gst-plugins-bad'

### ISSUE THREAD

**Issue by jpartain89** [rcmdnk/homebrew-file#202]
I am currently using an M2 mac on the Sonoma AppleSeed beta (14.0 Beta (23A5286i)), and when I attempt to run `brew file init` I get the below error messaging:

```bash
Traceback (most recent call last):
  File "/opt/homebrew/bin/brew-file", line 3599, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/bin/brew-file", line 3586, in main
    b.execute()
  File "/opt/homebrew/bin/brew-file", line 2907, in execute
    _ = self.initialize()
        ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/bin/brew-file", line 2124, in initialize
    self.get_installed_packages()
  File "/opt/homebrew/bin/brew-file", line 1929, in get_installed_packages
    p, info[p]
       ~~~~^^^
KeyError: 'gst-plugins-bad'
```

```bash
$ brew file version
Homebrew 4.0.28-141-gac93842
brew-file 9.0.12 11/Apr/2023```

Please let me know what other info you might need from me.

**Comment by rcmdnk** [comment]
Please run the following commands and show me the results.

```
$ brew list --formula|wc
$ brew list --formula | grep gst-plugins-bad
$ brew info
$ brew info --json=v1 gst-plugins-bad
$ brew info --json=v1 --installed | grep gst-plugins-bad
```

And I think gst-plugins-bad is a formula installed by external tap (it is not in the [homebrew-core](https://github.com/Homebrew/homebrew-core).
Could you tell me the tap?
