### ISSUE TITLE
`UnboundLocalError` running `brew file init` command

### ISSUE THREAD

**Issue by ian-h-chamberlain** [rcmdnk/homebrew-file#225]
Version info:
```console
$ brew file --version
Homebrew 4.1.14-13-gd0eef12
Homebrew/homebrew-core (git revision 4dcf92148c7; last commit 2023-10-03)
Homebrew/homebrew-cask (git revision 49e147a5f5; last commit 2023-07-05)
brew-file 9.0.14 08/Aug/2023
$ python3 --version
Python 3.11.5
```

This looks similar to #69 but that issue is obviously quite old, and I am also running a rather recent python version (3.11 that ships with macOS). Here's the traceback:

```console
$ brew file init 
Do you want to set a repository (y)? ((n) for local Brewfile). [y/n]: n
Traceback (most recent call last):
  File "/usr/local/bin/brew-file", line 3600, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/bin/brew-file", line 3587, in main
    b.execute()
  File "/usr/local/bin/brew-file", line 2908, in execute
    _ = self.initialize()
        ^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/brew-file", line 2125, in initialize
    self.get_installed_packages()
  File "/usr/local/bin/brew-file", line 1929, in get_installed_packages
    self.brewinfo.brew_list_opt[p] = self.helper.get_option(
                                     ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/brew-file", line 355, in get_option
    installed = self.get_installed(package, package_info)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/brew-file", line 344, in get_installed
    return installed
           ^^^^^^^^^
UnboundLocalError: cannot access local variable 'installed' where it is not associated with a value
```

Please let me know if you need another info to debug! I was hoping to start using this tool to manage packages but it's tough when I can't even get started :(

**Comment by rcmdnk** [comment]
Thanks for the report.
I think I could fix the bug but it is a bit unexpected case.

It seems some packages have no version information.

Could you please provide installed package list (just a result of `brew ls`)?
And if you have any pckages installed from other than homebrew-core tap or installed directly from formulae, the information will be helpful.

**Comment by ian-h-chamberlain** [comment]
I have quite a few installed, let me see if I can identify which ones are from custom taps etc.

<details>
<summary>`brew ls --full-name` output</summary>

```console
$ brew ls --full-name 
act                                     htop                                    nim
adns                                    icu4c                                   ninja
aom                                     imagemagick                             nmap
autoconf                                imath                                   node
automake                                isl                                     npth
awk                                     jansson                                 oniguruma
bash                                    jasper                                  openblas
bash-completion@2                       jbig2dec                                openexr
bash-git-prompt                         jemalloc                                openjdk
bat                                     jpeg                                    openjdk@8
bazelisk                                jpeg-turbo                              openjpeg
bdw-gc                                  jpeg-xl                                 openldap
berkeley-db                             jq                                      openssh
binaryen                                ldns                                    openssl@1.1
binutils                                libaec                                  openssl@3
bison                                   libarchive                              openstackclient
boost                                   libassuan                               p11-kit
boost-python                            libavif                                 pango
bpython                                 libb2                                   pcre
brew-gem                                libcbor                                 pcre2
brotli                                  libde265                                perl
buildifier                              libestr                                 pinentry
c-ares                                  libev                                   pinentry-mac
ca-certificates                         libevent                                pixman
cairo                                   libfastjson                             pkg-config
capstone                                libffi                                  popt
cffi                                    libfido2                                postgresql@11
clang-format                            libgcrypt                               protobuf@3.6
cmake                                   libgpg-error                            psutils
colima                                  libheif                                 pycparser
coreutils                               libidn                                  pyenv
cppcheck                                libidn2                                 pyenv-virtualenv
crosstool-ng                            libksba                                 pygments
cscope                                  liblinear                               python-certifi
ctags                                   liblqr                                  python-cryptography
curl                                    libmagic                                python-pytz
docker                                  libmetalink                             python@3.10
docker-buildx                           libmpc                                  python@3.11
docker-completion                       libnghttp2                              python@3.9
docker-credential-helper                libomp                                  pyyaml
double-conversion                       libpaper                                qemu
dtc                                     libpng                                  range-v3
dust                                    libpthread-stubs                        rbenv
duti                                    libraw                                  re2c
emscripten                              librsvg                                 readline
exercism                                libslirp                                ripgrep
fd                                      libsmi                                  rpm
firefoxpwa                              libsodium                               rsyslog
fish                                    libssh                                  rtmpdump
flatbuffers                             libssh2                                 rtx
flex                                    libtasn1                                ruby
fmt                                     libtermkey                              ruby-build
folly                                   libtiff                                 rustup-init
fontconfig                              libtool                                 screenresolution
freetype                                libunistring                            sd
fribidi                                 libusb                                  shared-mime-info
fzf                                     libuv                                   shellcheck
gawk                                    libvmaf                                 six
gcc                                     libvterm                                snappy
gcc@7                                   libx11                                  sqlite
gd                                      libxau                                  swig
gdb                                     libxcb                                  tbb
gdbm                                    libxdmcp                                tcl-tk
gdk-pixbuf                              libxext                                 telnet
gem-completely                          libxml2                                 texinfo
gettext                                 libxmlsec1                              thefuck
gflags                                  libxrender                              tinyxml2
gh                                      libyaml                                 tmux
ghc                                     lima                                    tree
ghostscript                             little-cms2                             tree-sitter
giflib                                  llvm                                    uchardet
git                                     lnav                                    unbound
git-crypt                               lrzip                                   unibilium
git-delta                               lua                                     upx
git-lfs                                 luajit                                  utf8proc
git-quick-stats                         luajit-openresty                        vde
glib                                    luarocks                                vim
glog                                    luv                                     wakeonlan
gmp                                     lz4                                     watch
gnu-sed                                 lzip                                    webp
gnu-tar                                 lzo                                     wget
gnupg                                   m4                                      x265
gnutls                                  make                                    x86_64-elf-binutils
go                                      mas                                     x86_64-elf-gcc
go@1.16                                 mkcert                                  xorgproto
go@1.18                                 mockery                                 xz
gobject-introspection                   mpdecimal                               yadm
golangci-lint                           mpfr                                    yaml-cpp
graphite2                               msgpack                                 yuicompressor
graphviz                                mtr                                     z3
grep                                    nativefier                              zig
groff                                   ncurses                                 zlib
gts                                     neofetch                                zstd
guile                                   neovim                                  d12frosted/emacs-plus/emacs-plus@29
harfbuzz                                net-snmp                                [private package]
haskell-stack                           netpbm                                  rcmdnk/file/brew-file
hdf5                                    nettle                                  shihanng/gig/gig
highway                                 nghttp2                                 srkomodo/tap/shadowfox-updater
appcleaner                    fork                          proxy-audio-device            syntax-highlight
balance-lock                  gimp                          qlimagesize                   termhere
bettertouchtool               google-chrome                 qlmarkdown                    virtualbox
betterzip                     hex-fiend                     remoteviewer                  visual-studio-code
discord                       inkscape                      signal                        visual-studio-code-insiders
disk-inventory-x              insomnia                      slack                         vlc
eqmac                         iterm2                        spotify                       wireshark
firefox                       keepassxc                     stretchly                     xquartz
flux                          krita                         sublime-text
font-input                    mactex                        syncthing
⏎                                                                                                                       
```

</details>

`brew tap`:
```
d12frosted/emacs-plus
homebrew/bundle
homebrew/cask
homebrew/cask-drivers
homebrew/cask-fonts
homebrew/cask-versions
homebrew/core
homebrew/services
homebrew/test-bot
ian-h-chamberlain/dotfiles
rcmdnk/file
shihanng/gig
srkomodo/tap
[private tap]
```

I also have one private tap for tools from my company that I've redacted, which is hosted on Github (and one package installed from that tap).

Offhand, I know these few things that might be unusual:
* Built `lnav` from source with `HOMEBREW_NO_INSTALL_FROM_API=1 brew reinstall --build-from-source lnav`, but it does come from `homebrew-core` originally
* `rpm` is pinned, and the only thing that shows up in `brew ls --pinned` output

Otherwise, I don't think there's anything else too unusual. If you have other specific commands I can provide output from, let me know.

Thanks for looking into this!

**Comment by rcmdnk** [comment]
Please try updated v9.0.15.

Though I could not reproduce the error, there are some suspicious points:

* The following packages are obsolete (?) and corresponding formulae do not exist, so I changed them as follows:  
    * boost-python -> boost-python3
    * portobuf@3.6 -> protobuf@3
    * gem-completely -> gem-completion
* Maybe these packages were installed in the past and kept, then brew could not find information.
    * It is better to update these packages if possible. 
* You installed font-input of ian-h-chamberlain/dotfiles/font-input instead of homebrew/homebrew-core/font-input
    * This may not related to the above error.
    * But brew-file may not understand the tap and make a Brewfile with the latter.

**Comment by ian-h-chamberlain** [comment]
Thanks for the quick turnaround!

Without changing anything in my current setup, I tried the new version and got a different error this time:
```console
$ brew file init
Do you want to set a repository (y)? ((n) for local Brewfile). [y/n]: n
Traceback (most recent call last):
  File "/usr/local/bin/brew-file", line 3601, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/bin/brew-file", line 3588, in main
    b.execute()
  File "/usr/local/bin/brew-file", line 2909, in execute
    _ = self.initialize()
        ^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/brew-file", line 2126, in initialize
    self.get_installed_packages()
  File "/usr/local/bin/brew-file", line 1931, in get_installed_packages
    p, info[p]
       ~~~~^^^
KeyError: 'please'
```

Also looking at `brew doctor` output I noticed these, which might be related to what you found as well:

```
Warning: Some installed kegs have no formulae!
This means they were either deleted or installed manually.
You should find replacements for the following formulae:
  boost-python
  gem-completely
  protobuf@3.6

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  gcc@7
  go@1.16
  go@1.18
  protobuf@3.6

Warning: You have the following deprecated, official taps tapped:
  Homebrew/homebrew-cask-drivers
Untap them with `brew untap`.
```

Would you like me to maintain this state for further testing, or should I try to clean up some of the packages you mentioned to get it working?

**Comment by rcmdnk** [comment]
It seems `brew leaves` command says an error message like **please XXX...**.

Maybe you can try `brew leaves` or `brew leaves  --installed-on-request`.

> Would you like me to maintain this state for further testing, or should I try to clean up some of the packages you mentioned to get it working?

Well, it seems the status is not normal and I would like to ask you to resolve these `brew doctor`'s statements.

**Comment by ian-h-chamberlain** [comment]
Ok, I fixed up the `brew doctor` issues but was still hitting this error. From what I can tell, `please` is an actual formula name, not some helper message output. It seems to get parsed as part of the `brew list --formula` output:

```
$ brew list --formula | grep -C3 please
pinentry-mac
pixman
pkg-config
please
popt
postgresql@11
protobuf@3
```

I stepped into a debugger to take a closer look, and I think the issue is that `brew info --installed` and `brew list --formula` are not a 1-to-1 match:
```console
$ brew info --json=v1 --installed | jq -r '.[].name' > installed.txt
[ichamberlain@ichamberlain-mbp](🍎) ~/Downloads
$ brew list --formula > formula.txt 
[ichamberlain@ichamberlain-mbp](🍎) ~/Downloads
$ diff installed.txt formula.txt 
220a221
> please
```

I then found this odd directory with only a single 0-byte oddly-named and -dated `LICENSE` file, which was maybe some kind of failed install or something?
```console
$ ls /usr/local/Cellar/please/
total 0
drwxrwxr-x    3 ichamberlain  admin    96B Mar  8  2022 ./
drwxrwxr-x  293 ichamberlain  admin   9.2K Oct  6 14:13 ../
-rw-r--r--    1 ichamberlain  admin     0B Dec 31  1969 15.17.1LICENSE
```

After removing the offending directory I was able to get further! I then ran into this:
```console
$ brew file  -V debug init
Do you want to set a repository (y)? ((n) for local Brewfile). [y/n]: n

##########################################################
# Initialize /Users/ichamberlain/.config/brewfile/Brewfile
##########################################################

[ERROR] Failed at command: /usr/local/bin/brew info --eval-all --json=v2
Error: Failure while executing; `/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.1.14-52-g8f7e06a\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 13.6\)\ curl/8.1.2 --header Accept-Language:\ en --retry 3 --fail --silent --location https://build.transmissionbt.com/job/trunk-mac/lastSuccessfulBuild/artifact/release/` exited with 35. Here's the output:
curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to build.transmissionbt.com:443
```

Eventually I figured out that was happening due to my VPN blocking access to that domain, and finally I was able to initialize the `Brewfile`! 

Thanks for your help and the initial bugfix, I am going to go ahead and close this but hopefully my experience might help someone debug if they run into a similar problem in the future.

Now to start actually using `brew-file`...

**Comment by rcmdnk** [comment]
> please is an actual formula name,

oh...

>  finally I was able to initialize the Brewfile!

:thumbsup:

>  hopefully my experience might help someone debug if they run into a similar problem in the future.

Anyway, there was an bug and it was fixed by your report.
Thanks!
