### ISSUE TITLE
`brew file update`でエラーが発生します

### ISSUE THREAD

**Issue by k-tada** [rcmdnk/homebrew-file#45]
`brew file update`を実行すると以下のエラーが発生します。
突如発生するようになったのですが、原因、回避方法等分かりましたら教えていただけますでしょうか。

```
$ brew file update
Traceback (most recent call last):
  File "/usr/local/bin/brew-file", line 3050, in <module>
    main()
  File "/usr/local/bin/brew-file", line 3047, in main
    b.execute()
  File "/usr/local/bin/brew-file", line 2710, in execute
    self.get_list()
  File "/usr/local/bin/brew-file", line 1557, in get_list
    False, False)[1][0]):
  File "/Users/tada/.anyenv/envs/pyenv/versions/3.5.0/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/Users/tada/.anyenv/envs/pyenv/versions/3.5.0/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/tada/.anyenv/envs/pyenv/versions/3.5.0/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by rcmdnk** [comment]
ちょっとパッとわからないのですが、

    brew info --json=v1 --installed

の結果を貼ってもらえますでしょうか？
恐らく沢山パッケージをインストールしていると大量に出るでしょうが、
取り敢えず最初の崇敬分載せていただければ、と。

**Comment by rcmdnk** [comment]
こちらでも一度`brew update`をした所同じエラーが出るようになりました。

    Warning: Calling Formula.sha1 is deprecated!
    Use Formula.sha256 instead.

みたいなwarningが出ていて、どうも一部のFormulaで古い仕様を使っていると出るみたいなんですが
このwarningも含めてjsonだと思って解析しようとしてエラーを吐いています。

なのでこの部分ではエラーは別途見るようにして動くようにしました。

v3.14.3で直っています。

**Comment by k-tada** [comment]
おぉ、迅速な対応ありがとうございますm(_ _)m
無事`brew file update`が通りました！
