### ISSUE TITLE
Yosemite で Failed to install mas

### ISSUE THREAD

**Issue by znz** [rcmdnk/homebrew-file#47]
OS X Yosemite (10.10.5) の環境で `brew file init` を実行すると `Failed to install mas` になります。
Xcode は 7.2.1 が入っていて、App Store を開いてみても Yosemite ではこれ以上更新できないようなのですが、どうすれば良いのでしょうか?

```
% brew file init
Do you want to set a repository (y)? ((n) for local Brewfile). [y/n]: n
$ command brew install mas
mas: A full installation of Xcode.app 7.3 is required to compile this software.
Installing just the Command Line Tools is not sufficient.
Xcode can be installed from the App Store.
Error: An unsatisfied requirement failed this build.

Failed to install mas
```

**Comment by rcmdnk** [comment]
勘違いかどこかで見たのか忘れましたが、Yosemite以降で`mas`が使えると思っていて
そのように設定していましたが、使えないと言うことなのでYosemiteの場合には`mas`をインストールせずに
直接探す方法を使うようにしてみました。

`brew update && brew upgrade`して試して頂けますか？

**Comment by znz** [comment]
今度は別のエラーになりました。

```
% brew file init
Do you want to set a repository (y)? ((n) for local Brewfile). [y/n]: n
Warning: nothing to list
You are using older OS X. mas is not used.
Traceback (most recent call last):
  File "/usr/local/bin/brew-file", line 3060, in <module>
    main()
  File "/usr/local/bin/brew-file", line 3057, in main
    b.execute()
  File "/usr/local/bin/brew-file", line 2696, in execute
    self.initialize()
  File "/usr/local/bin/brew-file", line 1716, in initialize
    self.get_list()
  File "/usr/local/bin/brew-file", line 1601, in get_list
    self.brewinfo.set_val("appstore_list", self.get_appstore_list())
  File "/usr/local/bin/brew-file", line 1516, in get_appstore_list
    for x in glob.glob(d + '/*/Contents/_MASReceipt/receipt')]
AttributeError: 'list' object has no attribute 'split'
```

**Comment by rcmdnk** [comment]
すいません、`mas`を使わない部分についてきちんとバリデーションしてませんでした。
今のバージョンでは動くようになってるはずです。

**Comment by znz** [comment]
修正ありがとうございます。
動くようになっているのを確認しました。
