### ISSUE TITLE
stdout is too slow; homebrew may appear like it's not doing anything

### ISSUE THREAD

**Issue by boneskull** [rcmdnk/homebrew-file#49]
not sure if it's blocking on something or this is an infinite/recursive loop:

```sh
$ brew install --force git
# the following command was issued by the brew-wrap script, afaict
$ command brew install --force git
# nothing happens here, so I sent a SIGINT
^CTraceback (most recent call last):
  File "/usr/local/bin/brew-file", line 3061, in <module>
    main()
  File "/usr/local/bin/brew-file", line 3058, in main
    b.execute()
  File "/usr/local/bin/brew-file", line 2692, in execute
    self.brew_cmd()
  File "/usr/local/bin/brew-file", line 1153, in brew_cmd
    True, True, False)
  File "/usr/local/bin/brew-file", line 837, in proc
    verbose_level=verbose_level)
  File "/usr/local/bin/brew-file", line 161, in proc
    for line in p.stdout:
KeyboardInterrupt
```

**Comment by boneskull** [comment]
upon further inspection `brew-wrap` is probably not the culprit

**Comment by boneskull** [comment]
OK, I see what's happening here.  looks like the output is buffered; I had tried this previously on a long chain of installs via `cask`.  the command issued aboved was my attempt at a trivial example. 

some of these casks want to prompt for superuser password.  it may have been waiting on `stdin` for my password without my knowledge.

**Comment by boneskull** [comment]
don't think so.  but I can improve the responsiveness.  PR incoming
