### ISSUE TITLE
Catch and handle KeyboardInterrupt gracefully

### ISSUE THREAD

**Issue by radeksimko** [rcmdnk/homebrew-file#85]
When a running `brew` command gets interrupted via `SIGINT` (`Ctrl+C`) brew-file currently prints out unnecessary stack trace, making it look like something terrible happened:

```
$ brew cask install homebrew/drivers/hp-easy-start
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
jruby
==> Tapping homebrew/drivers
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-drivers'...
Username for 'https://github.com': ^CTraceback (most recent call last):
  File "/usr/local/bin/brew-file", line 3363, in <module>
    main()
  File "/usr/local/bin/brew-file", line 3359, in main
    b.execute()
  File "/usr/local/bin/brew-file", line 2955, in execute
    self.brew_cmd()
  File "/usr/local/bin/brew-file", line 1406, in brew_cmd
    False, True, False, env=env)
  File "/usr/local/bin/brew-file", line 1021, in proc
    print_err=print_err, verbose=verbose, env=env)
  File "/usr/local/bin/brew-file", line 196, in proc
    for line in self.readstdout(p):
  File "/usr/local/bin/brew-file", line 156, in readstdout
    line = my_decode(proc.stdout.readline()).rstrip()
KeyboardInterrupt
```

I think that `KeyboardInterrupt` should be handled gracefully, like it is in Homebrew itself.

**Comment by rcmdnk** [comment]
I agree that it is useless to show them, especially for users.

ok, I updated to trap Ctlr-C and just exit with an error status.
